kind: pipeline
name: default

steps:
- name: Run rspec
  image: ruby:2.6.5
  commands:
    - gem install bundler
    - bundle
    - bundle exec rspec
  when:
    event:
      - pull_request
- name: Bump and tag
  image: quay.io/openware/sdk-tools:0.0.3
  environment:
    BRANCH_NAME: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile release:push
  when:
    event: [push]
    branch: [master]

image_pull_secrets:
  - dockerconfigjson
