version: '3.6'

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.${APP_DOMAIN}"
      traefik.port: 3000

  tower:
    image: quay.io/openware/wio:0.1.0
    user: "${UID}:${GID}"
    command: "-d /home/app/build -s 1"
    volumes:
      - ../vendor/tower:/home/app
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.${APP_DOMAIN}"
      traefik.port: 8080
